project_id = "szhfuosuldookhvmreti"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54325
api_url = "http://localhost:54321"

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
port = 54327
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
external_phone_enabled = false
sms_provider = "twilio"
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.metricool-api]
verify_jwt = true

[functions.metricool-sync]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54328
ip_version = "ipv4"

[analytics]
enabled = false
port = 54329
vector_port = 54330
gw_port = 54331