// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhrddccjkzzmgitivjas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocmRkY2Nqa3p6bWdpdGl2amFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjIzNDgsImV4cCI6MjA2ODMzODM0OH0.j1muhpEt_Q51skqC9ESLh6Jc-OdFTRtFTKS-N1IReaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});