// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szhfuosuldookhvmreti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6aGZ1b3N1bGRvb2todm1yZXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzU4NDgsImV4cCI6MjA2ODI1MTg0OH0.dqVMOnliktVVz5mhQbwVJtDcjQv2kFpAnnYcP_66YWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});